---
- include: repo.yaml

- name: Create mcrouter configuration
  template:
    src: templates/mcrouter.conf.j2
    dest: /etc/mcrouter.conf
    owner: root
    group: root
    mode: 0644

- name: Install mcrouter
  apt:
    name: "mcrouter={{ mcrouter_version }}"
    state: present

- name: Create systemd unit configuration
  template:
    src: templates/mcrouter.service.j2
    dest: etc/systemd/system/mcrouter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mcrouter

- name: create systemd directory for override haproxy value
  file:
    state: directory
    path: /etc/systemd/system/mcrouter.service.d

- name: increase number of openfiles and process limits
  template:
    src: systemd_override.conf.j2
    dest: /etc/systemd/system/mcrouter.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mcrouter
